### ISSUE TITLE
Fix dependencies compilations resolution

### ISSUE THREAD

**Issue by Xharos** [islands-wars/hub#1]
### Description

Fix (jfrog team URL) and core:build.gradle that doesn't send the fatJar to jfrog

### Informations

1. Code used
```java
compile 'fr.islandswars:core:0.2.9-develop'
```

**Expected behavior:** To compile obviously :)

### Versions

``0.1``

**Comment by Vinetos** [comment]
Should be fix. Please re-open it if not
